const CONSTANTS = {
  SOCKET_EVENTS: {
    NEW_MESSAGE: 'NEW_MESSAGE',
    NEW_MESSAGE_SUCCESS: 'NEW_MESSAGE_SUCCESS',
    NEW_MESSAGE_ERROR: 'NEW_MESSAGE_ERROR',
    EDIT_MESSAGE: 'EDIT_MESSAGE',
    EDIT_MESSAGE_SUCCESS:'EDIT_MESSAGE_SUCCESS',
    EDIT_MESSAGE_ERROR: 'EDIT_MESSAGE_ERROR',
    DELETE_MESSAGE: 'DELETE_MESSAGE',
    DELETE_MESSAGE_SUCCESS:'DELETE_MESSAGE_SUCCESS',
    DELETE_MESSAGE_ERROR: 'DELETE_MESSAGE_ERROR',
  },
};

export default CONSTANTS;
